### ISSUE TITLE
Physical movement

### ISSUE THREAD

**Issue by rooq** [NJIT-EmbeddedSystems/whiteboard-scanner-eraser#3]
We need to implement a solution to move the whole solution.
- Motors
- Servos
- Limit Switches

Notes:
- How do we program GPIO's?
- PWM operating voltage, and how to use it to control.
- Forward/backward's movements

**Comment by JSJ08** [comment]
I've posted a possible solution in the physical movement branch. Keep in mind I haven't used this library or a raspberry pi before so it likely won't work on the first shot but I won't really know what to fix until I'm able to test it with the actual parts. Also, if you try to check or verify the code it won't work because none of the input or output devices have been assigned pin numbers yet.
